# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Todolist' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todolist
  pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"
  pod 'MGSwipeTableCell'

  target 'TodolistTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodolistUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
